FROM node:20-alpine AS builder

WORKDIR /app

RUN npm install -g pnpm

COPY package*.json pnpm-lock.yaml* ./

RUN pnpm install

COPY . .

RUN pnpm run build

FROM node:20-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY --from=builder /app/package*.json /app/pnpm-lock.yaml* ./

RUN pnpm install --prod

COPY --from=builder /app/dist ./dist

COPY --from=builder /app/node_modules/.bin/ /app/node_modules/.bin/

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

CMD ["node", "dist/main"]